version: 2

models:
  - name: fct_trips
    description: "Main fact table with all high-quality trips. One row per trip."
    columns:
      - name: trip_id
        description: "Primary key — unique trip identifier"
        tests:
          - not_null

      - name: taxi_type
        description: "Taxi type (yellow, green, fhv, fhvhv)"
        tests:
          - not_null
          - accepted_values:
              values: ["yellow", "green", "fhv", "fhvhv"]

      - name: pickup_datetime
        description: "Trip start timestamp"
        tests:
          - not_null

      - name: is_high_quality_trip
        description: "Whether the trip passed all quality checks"
        tests:
          - not_null

  - name: fct_trips_daily
    description: "Daily aggregates by taxi type. One row per (trip_date, taxi_type)."
    columns:
      - name: trip_date
        description: "Trip date"
        tests:
          - not_null

      - name: taxi_type
        description: "Taxi type"
        tests:
          - not_null

      - name: total_trips
        description: "Total trips for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_distance_miles
        description: "Sum of trip distances"

      - name: total_revenue
        description: "Total revenue (yellow/green only)"

  - name: fct_trips_monthly
    description: "Monthly aggregates by taxi type. One row per (year, month, taxi_type)."
    columns:
      - name: year
        description: "Year"
        tests:
          - not_null

      - name: month
        description: "Month (1-12)"
        tests:
          - not_null

      - name: taxi_type
        description: "Taxi type"
        tests:
          - not_null

      - name: total_trips
        description: "Total trips for the month"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

      - name: total_revenue
        description: "Total revenue for the month (yellow/green only)"

      - name: days_with_trips
        description: "Number of days with recorded trips"
