# Raw layer sources — Iceberg tables partitioned by year/month

version: 2

sources:
  - name: raw
    database: iceberg
    schema: raw
    description: "Raw data layer with Iceberg format (ACID, time travel, schema evolution)"
    meta:
      owner: "data-team"
      source_url: "https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page"

    tables:
      - name: yellow_trips
        description: "NYC TLC Yellow Taxi trip records (traditional yellow cabs)"
        meta:
          contains_pii: false
          refresh_cadence: "daily"
        freshness:
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
        loaded_at_field: loaded_at

      - name: green_trips
        description: "NYC TLC Green Taxi trip records (boro taxis, outside Manhattan)"
        meta:
          contains_pii: false
          refresh_cadence: "daily"
        freshness:
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
        loaded_at_field: loaded_at

      - name: fhv_trips
        description: "NYC TLC For-Hire Vehicle trip records (base dispatched vehicles)"
        meta:
          contains_pii: false
          refresh_cadence: "daily"
        freshness:
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
        loaded_at_field: loaded_at

      - name: fhvhv_trips
        description: "NYC TLC High Volume For-Hire Vehicle trip records (Uber, Lyft, Via)"
        meta:
          contains_pii: false
          refresh_cadence: "daily"
        freshness:
          warn_after: {count: 2, period: day}
          error_after: {count: 5, period: day}
        loaded_at_field: loaded_at
